{"status":"OK","subtests":[{"name":"Observable constructor","status":"PASS"},{"name":"Subscriber interface is not constructible","status":"FAIL"},{"name":"subscribe() can be called with no arguments","status":"PASS"},{"name":"Observable constructor calls initializer on subscribe","status":"FAIL"},{"name":"Observable error path called synchronously","status":"FAIL"},{"name":"Observable should error if initializer throws","status":"FAIL"},{"name":"Subscription does not emit values after completion","status":"FAIL"},{"name":"Subscription does not emit values after error","status":"FAIL"},{"name":"Completing or nexting a subscriber after an error does nothing","status":"FAIL"},{"name":"Errors pushed to the subscriber that are not handled by the subscription are reported to the global","status":"FAIL"},{"name":"Errors thrown in the initializer that are not handled by the subscription are reported to the global","status":"PASS"},{"name":"Subscription reports errors that are pushed after subscriber is closed by completion","status":"FAIL"},{"name":"Errors thrown by initializer function after subscriber is closed by completion are reported","status":"FAIL"}]}