{"status":"OK","subtests":[{"name":"start: errors in start cause WritableStream constructor to throw","status":"FAIL"},{"name":"close: throwing method should cause writer close() and ready to reject","status":"FAIL"},{"name":"close: returning a rejected promise should cause writer close() and ready to reject","status":"FAIL"},{"name":"close: throwing getter should cause constructor to throw","status":"FAIL"},{"name":"write: throwing getter should cause write() and closed to reject","status":"FAIL"},{"name":"write: throwing method should cause write() and closed to reject","status":"FAIL"},{"name":"write: returning a promise that becomes rejected after the writer write() should cause writer write() and ready to reject","status":"FAIL"},{"name":"write: returning a rejected promise (second write) should cause writer write() and ready to reject","status":"FAIL"},{"name":"abort: non-function abort method with .apply","status":"FAIL"},{"name":"abort: throwing getter should cause abort() and closed to reject","status":"FAIL"},{"name":"abort: throwing method should cause abort() and closed to reject","status":"FAIL"}]}